---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/collections.yml
driver:
  name: docker
platforms:
  - name: bionic
    pre_build_image: true
    image: quay.io/paulfantom/molecule-systemd:ubuntu-18.04
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
  - name: focal
    pre_build_image: true
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /lib/systemd/systemd
  - name: stretch
    pre_build_image: true
    image: quay.io/paulfantom/molecule-systemd:debian-9
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
  - name: buster
    pre_build_image: true
    image: geerlingguy/docker-debian10-ansible:latest
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
  - name: centos8
    pre_build_image: true
    image: geerlingguy/docker-centos8-ansible:latest
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    groups:
      - python3
  - name: fedora
    pre_build_image: true
    image: mpaivabarbosa/molecule-systemd-fedora:32
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    groups:
      - python3
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: playbook.yml
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: testinfra
